#!/usr/bin/env bash

MTSG_HOME=$(realpath $(dirname $0)/..)
TEST_HOME=$MTSG_HOME/tmp/test

WRAPPER=$MTSG_HOME/test/bin/wrapper

oneTimeSetUp() {
    docker build --tag mtsg $MTSG_HOME/../..
}

setUp() {
    mkdir -p $TEST_HOME/in/vcfs/0
    cp $MTSG_HOME/test/fixtures/vcfs/* $TEST_HOME/in/vcfs/0
}

tearDown() {
    rm -r $TEST_HOME
}

test_wrapper() {
    $WRAPPER > /dev/null 2>&1
    assertEquals "wrapper failed" $? 0

    assertTrue "SJACT001_D.vcf does not exist" "[ -e $TEST_HOME/results/vcfs/SJACT001_D.vcf ]"
    assertTrue "SJACT002_D.vcf does not exist" "[ -e $TEST_HOME/results/vcfs/SJACT002_D.vcf ]"
    assertTrue "SJACT003_D.vcf does not exist" "[ -e $TEST_HOME/results/vcfs/SJACT003_D.vcf ]"

    assertTrue "mtsg.sample.sheet.txt does not exist" "[ -e $TEST_HOME/results/mtsg.sample.sheet.txt ]"
    assertTrue "mtsg.signatures.html does not exist" "[ -e $TEST_HOME/results/mtsg.signatures.html ]"
    assertTrue "mtsg.signatures.txt does not exist" "[ -e $TEST_HOME/results/mtsg.signatures.txt ]"
}

test_wrapper_with_sample_sheet() {
    SAMPLE_SHEET=$MTSG_HOME/test/fixtures/sample-sheet.txt
    mkdir -p $TEST_HOME/results
    cp $SAMPLE_SHEET $TEST_HOME/results/mtsg.sample-sheet.txt

    $WRAPPER "" $SAMPLE_SHEET > /dev/null 2>&1

    diff $SAMPLE_SHEET $TEST_HOME/results/mtsg.sample-sheet.txt
    assertEquals "sample sheet did not match input" $? 0
}

test_wrapper_with_invalid_min_burden() {
    $WRAPPER "" "" "" -1 > /dev/null 2>&1
    assertEquals "invalid min burden did not fail" $? 1
}

test_wrapper_with_invalid_min_contribution() {
    $WRAPPER "" "" "" "" -1 > /dev/null 2>&1
    assertEquals "invalid min contribution did not fail" $? 1
}

test_wrapper_with_no_prefix_and_one_file() {
    $WRAPPER $TEST_HOME/in/vcfs/0/sample.single.vcf > /dev/null 2>&1
    N_FILES=$(ls $TEST_HOME/results/sample.single* | wc -l)
    assertEquals "input basename not prepended to result filenames" $N_FILES 5
}

test_wrapper_with_prefix() {
    $WRAPPER "" "" "" "" "" ms > /dev/null 2>&1
    N_FILES=$(ls $TEST_HOME/results/ms* | wc -l)
    assertEquals "prefix override not prepended to result filenames" $N_FILES 5
}

test_wrapper_with_space_in_prefix() {
    $WRAPPER "" "" "" "" "" "mut spec" > /dev/null 2>&1
    assertEquals "prefixes with spaces failed" $? 0
}

test_wrapper_with_disable_column() {
    $WRAPPER "" "" "" "" "" "" 1 > /dev/null 2>&1
    assertFalse "sample unexpectedly exists" "[ -e $TEST_HOME/results/vcfs/SJACT002_D.vcf ]"
}

source shunit2
